### ISSUE TITLE
Sonic 2 scripts broken

### ISSUE THREAD

**Issue by alo3599homebrew** [RSDKModding/RSDKv4-Script-Decompilation#45]
when i play my sonic 2 game it crashes saying "operand not found: player_sonic_tails_a". i tried both google play and amazon data.rsdk files but no luck. plz fix i want extended camera
![Screenshot 2024-07-04 164228](https://github.com/RSDKModding/RSDKv4-Script-Decompilation/assets/151877156/1516e185-2069-448a-833f-31d2a4eb5cbc)

**Comment by MegAmi24** [comment]
You're using a mod that has not been updated to work with the latest version of the decompiled scripts. It's up to the mod creator to update their mod. Closing.
